source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'

gem 'sidekiq'
gem 'pg'

group :development do
  gem 'pry'
end
