source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'slim'
gem 'd3-rails'

gem 'delayed_job_active_record'
gem 'pg'

gem 'rollbar'

group :development do
  gem 'pry'
end
